//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SherlockdbEntities : DbContext
    {
        public SherlockdbEntities()
            : base("name=SherlockdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_asu_lead> t_asu_lead { get; set; }
        public virtual DbSet<t_authentication_token> t_authentication_token { get; set; }
        public virtual DbSet<t_buyer_master> t_buyer_master { get; set; }
        public virtual DbSet<t_buyer_mortgage_face> t_buyer_mortgage_face { get; set; }
        public virtual DbSet<t_buyer_product> t_buyer_product { get; set; }
        public virtual DbSet<t_buyer_product_criteria> t_buyer_product_criteria { get; set; }
        public virtual DbSet<t_buyer_product_face> t_buyer_product_face { get; set; }
        public virtual DbSet<t_common_leads> t_common_leads { get; set; }
        public virtual DbSet<t_common_leads_log> t_common_leads_log { get; set; }
        public virtual DbSet<t_debt_lead> t_debt_lead { get; set; }
        public virtual DbSet<t_define_category> t_define_category { get; set; }
        public virtual DbSet<t_equityrelease_lead> t_equityrelease_lead { get; set; }
        public virtual DbSet<t_hoax> t_hoax { get; set; }
        public virtual DbSet<t_ipi_lead> t_ipi_lead { get; set; }
        public virtual DbSet<t_life_lead> t_life_lead { get; set; }
        public virtual DbSet<t_loan_lead> t_loan_lead { get; set; }
        public virtual DbSet<t_logbookloan_lead> t_logbookloan_lead { get; set; }
        public virtual DbSet<t_mortgage_annual_income> t_mortgage_annual_income { get; set; }
        public virtual DbSet<t_mortgage_credit> t_mortgage_credit { get; set; }
        public virtual DbSet<t_mortgage_employee_status> t_mortgage_employee_status { get; set; }
        public virtual DbSet<t_mortgage_lead> t_mortgage_lead { get; set; }
        public virtual DbSet<t_mortgage_lead_log> t_mortgage_lead_log { get; set; }
        public virtual DbSet<t_mortgage_period_term> t_mortgage_period_term { get; set; }
        public virtual DbSet<t_mortgage_property_type> t_mortgage_property_type { get; set; }
        public virtual DbSet<t_mortgage_rate_type> t_mortgage_rate_type { get; set; }
        public virtual DbSet<t_mortgage_repayment> t_mortgage_repayment { get; set; }
        public virtual DbSet<t_pmi_lead> t_pmi_lead { get; set; }
        public virtual DbSet<t_postcode> t_postcode { get; set; }
        public virtual DbSet<t_ppi_lead> t_ppi_lead { get; set; }
        public virtual DbSet<t_product_master> t_product_master { get; set; }
        public virtual DbSet<t_product_website> t_product_website { get; set; }
        public virtual DbSet<t_property_location> t_property_location { get; set; }
        public virtual DbSet<t_role_master> t_role_master { get; set; }
        public virtual DbSet<t_sme_mi_lead> t_sme_mi_lead { get; set; }
        public virtual DbSet<t_solar_lead> t_solar_lead { get; set; }
        public virtual DbSet<t_stage_master> t_stage_master { get; set; }
        public virtual DbSet<t_status_type_master> t_status_type_master { get; set; }
        public virtual DbSet<t_transfer_log> t_transfer_log { get; set; }
        public virtual DbSet<t_user_master> t_user_master { get; set; }
        public virtual DbSet<t_user_role> t_user_role { get; set; }
        public virtual DbSet<t_website_master> t_website_master { get; set; }
    }
}
