//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_buyer_product_criteria
    {
        public int buyer_product_criteria_id { get; set; }
        public int product_id { get; set; }
        public int buyer_id { get; set; }
    
        public virtual t_buyer_master t_buyer_master { get; set; }
        public virtual t_product_master t_product_master { get; set; }
    }
}
