//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_buyer_product_face
    {
        public int buyer_product_face_id { get; set; }
        public int product_id { get; set; }
        public string product_column_name { get; set; }
        public string expected_column_name { get; set; }
        public bool excluded { get; set; }
    
        public virtual t_product_master t_product_master { get; set; }
    }
}
