//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_buyer_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_buyer_master()
        {
            this.t_buyer_mortgage_face = new HashSet<t_buyer_mortgage_face>();
            this.t_buyer_product_criteria = new HashSet<t_buyer_product_criteria>();
            this.t_buyer_product = new HashSet<t_buyer_product>();
            this.t_transfer_log = new HashSet<t_transfer_log>();
        }
    
        public int buyer_id { get; set; }
        public string buyer_name { get; set; }
        public string buyer_address { get; set; }
        public string buyer_pincode { get; set; }
        public string buyer_poc_name { get; set; }
        public string buyer_contact_number { get; set; }
        public string buyer_poc_contact_number { get; set; }
        public string buyer_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_buyer_mortgage_face> t_buyer_mortgage_face { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_buyer_product_criteria> t_buyer_product_criteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_buyer_product> t_buyer_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_transfer_log> t_transfer_log { get; set; }
    }
}
