//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_buyer_mortgage_face
    {
        public int buyer_mortgage_face_id { get; set; }
        public int buyer_id { get; set; }
        public int age { get; set; }
        public int employment_status { get; set; }
        public int period_term { get; set; }
        public int property_value { get; set; }
        public int loan_value { get; set; }
        public int product_id { get; set; }
        public int current_debt { get; set; }
        public int property_location { get; set; }
        public int credit_history { get; set; }
        public int annual_income { get; set; }
        public bool miss_any_loan { get; set; }
        public bool had_bankruptcy { get; set; }
        public bool applied_iva { get; set; }
        public bool had_ccj { get; set; }
    
        public virtual t_buyer_master t_buyer_master { get; set; }
        public virtual t_product_master t_product_master { get; set; }
    }
}
