//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_common_leads_log
    {
        public int common_log_id { get; set; }
        public int lead_id { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string city { get; set; }
        public string postcode { get; set; }
        public string Home_Mobile_Phone1 { get; set; }
        public string Home_Mobile_Phone2 { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public int product_id { get; set; }
        public string ip_address { get; set; }
        public string source { get; set; }
        public string match_type { get; set; }
        public string keyword { get; set; }
        public int status_id { get; set; }
        public System.DateTime cretaed_on { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<int> updtaed_by { get; set; }
        public Nullable<int> stage_id { get; set; }
    
        public virtual t_product_master t_product_master { get; set; }
        public virtual t_stage_master t_stage_master { get; set; }
        public virtual t_status_type_master t_status_type_master { get; set; }
        public virtual t_user_master t_user_master { get; set; }
        public virtual t_user_master t_user_master1 { get; set; }
    }
}
