//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class t_common_leads
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_common_leads()
        {
            this.t_asu_lead = new HashSet<t_asu_lead>();
            this.t_debt_lead = new HashSet<t_debt_lead>();
            this.t_equityrelease_lead = new HashSet<t_equityrelease_lead>();
            this.t_ipi_lead = new HashSet<t_ipi_lead>();
            this.t_life_lead = new HashSet<t_life_lead>();
            this.t_loan_lead = new HashSet<t_loan_lead>();
            this.t_logbookloan_lead = new HashSet<t_logbookloan_lead>();
            this.t_mortgage_lead_log = new HashSet<t_mortgage_lead_log>();
            this.t_mortgage_lead = new HashSet<t_mortgage_lead>();
            this.t_pmi_lead = new HashSet<t_pmi_lead>();
            this.t_ppi_lead = new HashSet<t_ppi_lead>();
            this.t_sme_mi_lead = new HashSet<t_sme_mi_lead>();
            this.t_solar_lead = new HashSet<t_solar_lead>();
            this.t_transfer_log = new HashSet<t_transfer_log>();
        }
    
        public int lead_id { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string city { get; set; }
        public string postcode { get; set; }
        public string Home_Mobile_Phone1 { get; set; }
        public string Home_Mobile_Phone2 { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public int product_id { get; set; }
        public string ip_address { get; set; }
        public string source { get; set; }
        public string match_type { get; set; }
        public string keyword { get; set; }
        public int status_id { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<int> updtaed_by { get; set; }
        public Nullable<int> website_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_asu_lead> t_asu_lead { get; set; }
        public virtual t_product_master t_product_master { get; set; }
        public virtual t_status_type_master t_status_type_master { get; set; }
        public virtual t_user_master t_user_master { get; set; }
        public virtual t_user_master t_user_master1 { get; set; }
        public virtual t_website_master t_website_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_debt_lead> t_debt_lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_equityrelease_lead> t_equityrelease_lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_ipi_lead> t_ipi_lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_life_lead> t_life_lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_loan_lead> t_loan_lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_logbookloan_lead> t_logbookloan_lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_mortgage_lead_log> t_mortgage_lead_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_mortgage_lead> t_mortgage_lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_pmi_lead> t_pmi_lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_ppi_lead> t_ppi_lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_sme_mi_lead> t_sme_mi_lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_solar_lead> t_solar_lead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_transfer_log> t_transfer_log { get; set; }

        [NotMapped]
        public string product_name { get; set; }

    }
}
