//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_debt_lead
    {
        public int debt_lead_id { get; set; }
        public int lead_id { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public int age { get; set; }
        public int employement_status { get; set; }
        public int resinedtial_location { get; set; }
        public int total_creditors { get; set; }
        public Nullable<int> debt_type { get; set; }
        public int total_unsecured_debt { get; set; }
        public int monthly_repayment { get; set; }
        public Nullable<int> monthly_income { get; set; }
        public Nullable<int> monthly_disposable { get; set; }
        public int debt_residential_status_id { get; set; }
    
        public virtual t_common_leads t_common_leads { get; set; }
    }
}
