//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_life_lead
    {
        public int life_lead_id { get; set; }
        public int lead_id { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string insurance_type_id { get; set; }
        public int premium_type_id { get; set; }
        public int age { get; set; }
        public string period { get; set; }
        public string amount { get; set; }
        public string smoker { get; set; }
        public string partner_first_name { get; set; }
        public string partner_last_name { get; set; }
        public string partner_smoker { get; set; }
        public Nullable<System.DateTime> partner_dob { get; set; }
        public string single_ownership { get; set; }
        public string critical_illness { get; set; }
    
        public virtual t_common_leads t_common_leads { get; set; }
    }
}
