//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_loan_lead
    {
        public int loan_lead_id { get; set; }
        public int lead_id { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public int age { get; set; }
        public int employment_status { get; set; }
        public int period { get; set; }
        public string property_value { get; set; }
        public string loan_value { get; set; }
        public Nullable<int> loan_type { get; set; }
        public int loan_purpose_id { get; set; }
        public string home_owner { get; set; }
        public string mortgage_balance { get; set; }
        public string query_string { get; set; }
        public string marital_status { get; set; }
        public int country_of_residance { get; set; }
        public int annual_income { get; set; }
        public int credit_rating { get; set; }
        public string loan_guarantor { get; set; }
        public string been_in_debt { get; set; }
        public Nullable<int> total_creditor { get; set; }
        public System.DateTime address_start_date { get; set; }
        public string occupation { get; set; }
        public string employer_name { get; set; }
        public Nullable<System.DateTime> employer_since { get; set; }
        public string previous_address { get; set; }
        public string previous_city { get; set; }
        public string previous_postcode { get; set; }
        public Nullable<System.DateTime> previous_address_since { get; set; }
    
        public virtual t_common_leads t_common_leads { get; set; }
    }
}
