//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_logbookloan_lead
    {
        public int logbookloan_lead_id { get; set; }
        public int lead_id { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public int age { get; set; }
        public int country_of_residence { get; set; }
        public string car_make { get; set; }
        public string car_model { get; set; }
        public string car_registration_year { get; set; }
        public string number_plate { get; set; }
        public string current_mileage { get; set; }
        public string clear_of_finance { get; set; }
        public string contact_time { get; set; }
        public int loan_value { get; set; }
    
        public virtual t_common_leads t_common_leads { get; set; }
    }
}
