//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_mortgage_lead
    {
        public int mortgage_lead_id { get; set; }
        public int lead_id { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public int age { get; set; }
        public int employment_status { get; set; }
        public int period_term { get; set; }
        public int property_value { get; set; }
        public int loan_value { get; set; }
        public int current_debt { get; set; }
        public int property_type { get; set; }
        public int property_location { get; set; }
        public int credit_history { get; set; }
        public int annual_income { get; set; }
        public bool miss_any_loan { get; set; }
        public bool had_bankruptcy { get; set; }
        public bool applied_iva { get; set; }
        public bool had_ccj { get; set; }
        public int rate_id { get; set; }
        public int repayment_id { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<int> updtaed_by { get; set; }
    
        public virtual t_common_leads t_common_leads { get; set; }
        public virtual t_mortgage_annual_income t_mortgage_annual_income { get; set; }
        public virtual t_mortgage_credit t_mortgage_credit { get; set; }
        public virtual t_mortgage_employee_status t_mortgage_employee_status { get; set; }
        public virtual t_mortgage_period_term t_mortgage_period_term { get; set; }
        public virtual t_mortgage_property_type t_mortgage_property_type { get; set; }
        public virtual t_mortgage_rate_type t_mortgage_rate_type { get; set; }
        public virtual t_mortgage_repayment t_mortgage_repayment { get; set; }
        public virtual t_property_location t_property_location { get; set; }
    }
}
