//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_product_website
    {
        public int product_website_id { get; set; }
        public int product_id { get; set; }
        public int website_id { get; set; }
    
        public virtual t_product_master t_product_master { get; set; }
        public virtual t_website_master t_website_master { get; set; }
    }
}
