//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_product_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_product_master()
        {
            this.t_buyer_mortgage_face = new HashSet<t_buyer_mortgage_face>();
            this.t_buyer_product = new HashSet<t_buyer_product>();
            this.t_buyer_product_criteria = new HashSet<t_buyer_product_criteria>();
            this.t_buyer_product_face = new HashSet<t_buyer_product_face>();
            this.t_common_leads = new HashSet<t_common_leads>();
            this.t_common_leads_log = new HashSet<t_common_leads_log>();
            this.t_product_website = new HashSet<t_product_website>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int parent_product_id { get; set; }
        public bool product_deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_buyer_mortgage_face> t_buyer_mortgage_face { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_buyer_product> t_buyer_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_buyer_product_criteria> t_buyer_product_criteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_buyer_product_face> t_buyer_product_face { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_common_leads> t_common_leads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_common_leads_log> t_common_leads_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_product_website> t_product_website { get; set; }
    }
}
