//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sme_mi_lead
    {
        public int sme_mi_lead_id { get; set; }
        public int lead_id { get; set; }
        public string company_name { get; set; }
        public int no_of_employee { get; set; }
        public string existing_policy { get; set; }
        public int cover_type { get; set; }
        public string company_address { get; set; }
        public string company_city { get; set; }
        public string company_postcode { get; set; }
    
        public virtual t_common_leads t_common_leads { get; set; }
    }
}
