//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_solar_lead
    {
        public int solar_lead_id { get; set; }
        public int lead_id { get; set; }
        public int property_type { get; set; }
        public int home_owner { get; set; }
    
        public virtual t_common_leads t_common_leads { get; set; }
    }
}
