//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_status_type_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_status_type_master()
        {
            this.t_common_leads = new HashSet<t_common_leads>();
            this.t_common_leads_log = new HashSet<t_common_leads_log>();
            this.t_transfer_log = new HashSet<t_transfer_log>();
        }
    
        public int status_id { get; set; }
        public string status_name { get; set; }
        public string status_desc { get; set; }
        public System.DateTime creation_datetime { get; set; }
        public Nullable<System.DateTime> last_updated_datetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_common_leads> t_common_leads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_common_leads_log> t_common_leads_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_transfer_log> t_transfer_log { get; set; }
    }
}
