//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_transfer_log
    {
        public int transfer_log_id { get; set; }
        public System.DateTime generated_datetime { get; set; }
        public System.DateTime transfer_datetime { get; set; }
        public int buyer_id { get; set; }
        public int lead_id { get; set; }
        public Nullable<int> buyer_return_lead_id { get; set; }
        public string buyer_end_status { get; set; }
        public int status_id { get; set; }
        public string msg_returned { get; set; }
    
        public virtual t_buyer_master t_buyer_master { get; set; }
        public virtual t_common_leads t_common_leads { get; set; }
        public virtual t_status_type_master t_status_type_master { get; set; }
    }
}
